name: gloriabash
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chewie: ^1.2.2
  video_player: ^2.2.6
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  carousel_slider:
  youtube_player_flutter: ^8.0.0
  flutter_neumorphic: ^3.2.0
  rxdart: ^0.27.0
  dio: ^4.0.0-beta7
  path_provider: ^2.0.1
  http: ^0.13.0
  provider: ^6.0.0
  file: ^6.1.0
  uri: ^1.0.0
  url_launcher: ^6.1.3
  share: ^2.0.4
  google_mobile_ads: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_web_compilers: ">=2.0.0 <3.0.0"
  pedantic: ^1.11.0
  flutter_lints: ^2.0.0


  assets_audio_player:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf    
